# Server
server:
  port: 8766
 
#spring
spring: 
  data: 
    mongodb: 
      uri: mongodb://192.168.184.128:27017/amcloud
      database: amcloud

#eureka
eureka:
  instance:
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}

security:
  user:
    name: user
    password: password
  basic: 
    enabled: false
management:
  security:
    enabled: false
